#!/bin/bash

# To go work properly
export GOROOT=/usr/local/go
export GOPATH=/home/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# For production
# export GIN_MODE=release
# export MODE=release

# Remove and clone repository again
rm $GOPATH/src/github.com/prixplus/admin -rf
go get github.com/prixplus/admin

# Install admin server
go install github.com/prixplus/admin

# Kill server process and run it again
pkill admin
admin > /home/go/out.log
